version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started 
      - echo Building the Docker image...          
      - docker build -t $abcdefs:$CODEBUILD_WEBHOOK_HEAD_REF-$CODEBUILD_BUILD_NUMBER Dockerfile .
